### ISSUE TITLE
version.sexp

### ISSUE THREAD

**Issue by jgarte** [Lisp-Stat/dfio#8]
Hi,

Is this a file that it reads the version from located somewhere? 

https://github.com/Lisp-Stat/dfio/blob/f7984b792bf4d9010083db08472bc84d2d31430c/dfio.asd#L5

Do you happen to know the current version for this package?

**Comment by jgarte** [comment]
I just realized that this package must be missing the `version.sexp` file because this package has it:

https://github.com/Lisp-Stat/cephes.cl/blob/master/version.sexp

**Comment by snunez1** [comment]
No longer using version.sexp
